#ifndef _JBACIDEMO_IDL_
#define _JBACIDEMO_IDL_
#include <acscomponent.idl>
#pragma prefix "alma"

module demo
{
  interface JBaciDemo : ACS::ACSComponent
  {
    string sayHola();

    string sayHolaWithParameters(in string inString,
				 inout double inoutDouble,
				 out long outInt);
  };
};
#endif
